
development:
  adapter: postgresql
  encoding: unicode
  database: stack_uberflow_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: stack_uberflow_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: stack_uberflow_production
  pool: 5
  timeout: 5000
